set number
set relativenumber
set numberwidth=4
set indentexpr=
set cursorline
syntax enable 
let $PAGER=''
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
command Wq wq
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> \textOmega
imap <down> \textpm
imap <left> <nop>
imap <right> <nop>
nnoremap k kzz
nnoremap j jzz
nnoremap p pzz
nnoremap P Pzz
"let g:airline_theme='one'
colorscheme nord
"set background=dark
"let g:solarized_termcolors=256
"let g:solarized_termtrans=1
"call togglebg#map("<F5>")
